apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuzzle
  annotations:
    cert-manager.io/issuer: zerossl
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-security@kubernetescrd
    traefik.ingress.kubernetes.io/router.tls.options: {{ .Release.Namespace }}-tlsoptions@kubernetescrd
spec:
  tls:
  - secretName: {{ .Values.project }}.kuzzle.{{ .Values.environment }}
    hosts:
    - {{ .Values.project }}.kuzzle.{{ .Values.environment }}.rolder.app
  rules:
  - host: {{ .Values.project }}.kuzzle.{{ .Values.environment }}.rolder.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kuzzle
            port:
              name: kuzzle