apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: kuzzle
  labels:
    app: kuzzle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuzzle
  serviceName: kuzzle
  template:
    metadata:
      labels:
        app: kuzzle
    spec:      
      containers:
        - name: kuzzle
          image: kuzzleio/kuzzle-runner:{{ .Chart.AppVersion }}
          command: ["bash", "-c", "npm install && npm run build && node /var/app/app.js"]
          env:
            - name: kuzzle_services__storageEngine__client__node
              value: http://kuzzle-els:9200
            - name: kuzzle_services__internalCache__node__host
              value: kuzzle-redis
            - name: kuzzle_services__memoryStorage__node__host
              value: kuzzle-redis
            - name: NODE_ENV
              value: production
          ports:
            - name: kuzzle
              containerPort: 7512
          volumeMounts:
            - name: kuzzle-data
              mountPath: /var/app
  volumeClaimTemplates:
    - metadata:
        name: kuzzle-data
        labels:
          app: kuzzle
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 500Mi
        storageClassName: longhorn-r2
---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: kuzzle-redis
  labels:
    app: kuzzle-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuzzle-redis
  serviceName: kuzzle-redis
  template:
    metadata:
      labels:
        app: kuzzle-redis
    spec:      
      containers:
        - name: kuzzle-redis
          image: redis:6
          command: ["redis-server","--appendonly","yes"]
          ports:
            - name: kuzzle-redis
              containerPort: 6379
          volumeMounts:
            - name: kuzzle-redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: kuzzle-redis-data
        labels:
          app: kuzzle-redis
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 500Mi
        storageClassName: longhorn-r2
---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: kuzzle-els
  labels:
    app: kuzzle-els
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuzzle-els
  serviceName: kuzzle-els
  template:
    metadata:
      labels:
        app: kuzzle-els
    spec:      
      containers:
        - name: kuzzle-els
          image: kuzzleio/elasticsearch:7
          ports:
            - name: kuzzle-els
              containerPort: 9200
          volumeMounts:
            - name: kuzzle-els-data
              mountPath: /usr/share/elasticsearch/data
      securityContext:
            fsGroup: 0
            runAsUser: 1000
            runAsGroup: 0
  volumeClaimTemplates:
    - metadata:
        name: kuzzle-els-data
        labels:
          app: kuzzle-els
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 5Gi
        storageClassName: longhorn-r2