apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: security
spec:
  headers:
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
    forceSTSHeader: true
    customResponseHeaders:
      Access-Control-Allow-Origin: '*'
      Access-Control-Allow-Methods: 'GET, POST, OPTIONS'
      Access-Control-Allow-Headers: 'Content-Type, Authorization'